import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Navigation from "../components/Navigation/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Travelly-website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navigation_div}>
        <Navigation/>

      </div>
      </>
      
  )
}

export default Home
