import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Navigation from "../components/Navigation/index";
import Hero from "../components/Hero";

import Working from "../components/Working";

import Faq from "../components/Faq/index";

import Footer from "../components/Footer/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Travelly-website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />

      <Working />

      <Faq />

      <Footer />
    </>
  );
};

export default Home;
